# Conclusion / Summary Takeaways

In visualizing the map of the United States to discover patterns for leading cause of death per state, there is 2 primary leading causes of death: heart disease and cancer. Throughout the years of 2000 to 2017, Washington state was consistently had a leading cause of death for cancer whereas other states went back and forth. One idea that comes to mind for this pattern is that Washington is known for cancer research and lots of patients move there. I do not believe there is a big enough indication to think that people residing in Washington have a big enough lifestyle change to be different from other states which lead in heart disease. 

In the data visualization of the line graph, I was able to discover how much of the date showed that heart disease had overall higher death rates compared to the other two leading causes. The other leading cause included cancer, which mostly falls closer to the death rates of heart disease, especially in between 2010 and 2015. The third leading cause, stroke, also had high death rates, but were not as high as the two aforementioned causes. The broader implications of this insight include the overall patterns of death in which citizens of the United States are most susceptible to falling under. This is an important aspect of the gathered insight that the audience must consider because it may or may not affect themselves, as well as the people around them, which is the most important takeaway from this insight. Because of this feat, the information from our project can be especially broad in the sense that many people can benefit from understanding and interpreting our data visualizations. 

In the bar chart data visualization, heart disease is shown to be the leading cause of death every year. The second leading cause of death is cancer, and although it was never shown to be number one, it came very close to it in 2014. In the early years, all the other causes had shallow bars, but as time passed, they slowly increased, some more than others. This is important because it shows the drastic difference in deaths from each cause, which helps us see which causes we need to pay more attention to. 